# Name should be .travis.yml
sudo: required
services:
  - docker
  
before_install:
  - docker build -t aldam1r/docker-react -f Docker.dev .

script:
 - docker run -e CI=true aldam1r/docker-react npm run test