# Name must be .travis.yml to work. (similar to .gitlab-ci.yml)

# In case of error: "rakefile noty found"
# language: generic

sudo: required
services:
  - docker
  
before_install:
  - docker build -t aldam1r/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aldam1r/docker-react npm run test